### ISSUE TITLE
How do i use the latest version in a workflow?

### ISSUE THREAD

**Issue by pcroland** [adang1345/PythonWin7#23]
https://github.com/pcroland/deew/blob/main/.github/workflows/build.yaml
This is the current workflow for a project of mine.
```yaml
  windows-build:
    name: Windows
    runs-on: windows-latest
    needs: linux-build

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up libraries
        run: |
          python -m pip install wheel poetry
          python -m pip install "https://github.com/pcroland/Pyinstaller-Builds/releases/download/PyInstaller/pyinstaller-6.3.0-py3-none-win_amd64.whl"
          python -m pip install .

      - name: Fetch version
        run: |
          $version=$(python -c "print(open('changelog.md', 'r').read().split('\n')[0].split(' ')[2].replace(':', ''))")
          echo "Version: $version"
          echo "RELEASE_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Build
        run: |
          pyinstaller -F __main__.py -n deew --icon logo/icon.ico
```
I would like to be able to build a binary with the latest Python that runs on Win7 aswell.
Do i need https://github.com/adang1345/PythonWin7/blob/master/3.12.1/python-3.12.1-embed-amd64.zip or https://github.com/adang1345/PythonWin7/blob/master/3.12.1/python-3.12.1-amd64-full.exe to achieve it?

**Comment by adang1345** [comment]
I think the easiest solution would be to use the NuGet package because that is meant for CI workflows. First remove the usage of the the `actions/setup-python` action. Then write your own commands that install https://github.com/adang1345/PythonWin7/blob/master/3.12.1/python.3.12.1.nupkg. See the README for how to install that package.

Another option would be to use https://github.com/adang1345/PythonWin7/blob/master/3.12.1/python-3.12.1-amd64-full.exe. See https://docs.python.org/3/using/windows.html#installing-without-ui for instructions on how to install it using the command line.

The embeddable ZIP package is not the best option for your case because it is difficult to use `pip` with it.

**Comment by pcroland** [comment]
Thanks, I'll try them out.

**Comment by pcroland** [comment]
https://github.com/pcroland/deew/actions/runs/7379021076/job/20074810375
Seems like I could install 3.12.1 with:
```yaml
      - name: Set up Python
        run: |
          Invoke-WebRequest -Uri "https://github.com/adang1345/PythonWin7/raw/master/3.12.1/python-3.12.1-amd64-full.exe" -OutFile "python-installer.exe"
          ./python-installer.exe /quiet InstallAllUsers=1 PrependPath=1 Include_test=0
```
But it threw an error saying: `ERROR: Package 'deew' requires a different Python: 3.9.13 not in '<3.13,>=3.10'`
Does 3.12.1 has a `3.9.13` version string somewhere which causes the build to fail or I didn't install it properly?

**Comment by pcroland** [comment]
```yaml
      - name: Set up Python
        run: |
          Invoke-WebRequest -Uri "https://github.com/adang1345/PythonWin7/raw/master/3.12.1/python.3.12.1.nupkg" -OutFile "python.3.12.1.nupkg"
          mkdir "C:\custom_python"
          nuget install python -Source "python.3.12.1.nupkg" -OuputDirectory C:\custom_python
          $env:Path += ";C:\custom_python"
          $env:Path += ";C:\custom_python\Scripts"
          python --version
```
nuget didn't work either.

**Comment by adang1345** [comment]
Changes to `PATH` do not take effect in later workflow steps. See https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-system-path.

**Comment by pcroland** [comment]
```yaml
      - name: Set up Python
        run: |
          Invoke-WebRequest -Uri "https://github.com/adang1345/PythonWin7/raw/master/3.12.1/python.3.12.1.nupkg" -OutFile "python.3.12.1.nupkg"
          mkdir "C:\custom_python"
          nuget install python -Source "python.3.12.1.nupkg" -OuputDirectory "C:\custom_python"
          echo "C:\custom_python" >> $GITHUB_PATH
          echo "C:\custom_python\Scripts" >> $GITHUB_PATH
          python --version
```
![img](https://telegra.ph//file/ed8244dc4d891f18490ef.png)
https://github.com/pcroland/deew/actions/runs/7386651953/job/20093726883

**Comment by pcroland** [comment]
Oh, there's a typo in the readme: `-OuputDirectory` -> `-OutputDirectory`, but still:
`The specified source 'python.3.12.1.nupkg' is invalid. Please provide a valid source.`

**Comment by adang1345** [comment]
You are using the wrong argument for `-Source`. See https://github.com/adang1345/PythonWin7?tab=readme-ov-file#nuget-packages. The instructions say to use `%cd%` if running in Command Prompt. Since you're using PowerShell, you'll need to get the current working directory in a different manner.

Also, I think it's clear at this point that the installers in this repository are working correctly, so I'm going to let you debug your workflow.

**Comment by adang1345** [comment]
I updated the README to fix the typo, and I added instructions for PowerShell.

**Comment by pcroland** [comment]
```yaml
      - name: Set up Python
        run: |
          Invoke-WebRequest -Uri "https://github.com/adang1345/PythonWin7/raw/master/3.12.1/python.3.12.1.nupkg" -OutFile "python.3.12.1.nupkg"
          mkdir "C:\custom_python"
          nuget install python -Source $(Get-Location) -OutputDirectory "C:\custom_python\"
          echo "C:\custom_python" >> $GITHUB_PATH
          echo "C:\custom_python\Scripts" >> $GITHUB_PATH
          python --version
```
Managed to install, used `$GITHUB_PATH` but it still reports 3.9.13.

**Comment by pcroland** [comment]
```yaml
name: Build and publish

env:
  PY_PATH:

on:
  repository_dispatch:

jobs:
  windows-build:
    name: Windows
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        run: |
          Invoke-WebRequest -Uri "https://github.com/adang1345/PythonWin7/raw/master/3.12.1/python.3.12.1.nupkg" -OutFile "python.3.12.1.nupkg"
          mkdir "C:\pywin7"
          nuget install python -Source $(Get-Location) -OutputDirectory "C:\pywin7\"
          echo "C:\pywin7\python.3.12.1\tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          python --version

      - name: Set up libraries
        run: |
          python -m pip install wheel poetry
          python -m pip install "https://github.com/pcroland/Pyinstaller-Builds/releases/download/PyInstaller/pyinstaller-6.3.0-py3-none-win_amd64.whl"
          python -m pip install .

      - name: Build
        run: |
          python -m PyInstaller -F __main__.py -n deew --icon logo/icon.ico
```
Finally. Maybe you could add this in the readme as an example.
